services:
  - type: web
    name: web
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app.main:app" -w 4 -b 0.0.0.0:$PORT
